version: '2.1'

volumes:
  files:
    driver: local
  mysql-owncloud:
    driver: local
  backup-owncloud:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    build: owncloud/. 
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mysql
      - redis

    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  # #enable provisioning container to fill data structures
  # provisioning:
  #  build: mysql/provisioning/.
  #  depends_on:
  #    - mysql

  mysql:
    build: mysql/.
    restart: always
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-owncloud:/var/lib/mysql
      - backup-owncloud:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis