---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: ownclouddata-prod
   labels:
    app: owncloud
spec:
  volumeMode: Filesystem
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "ownclouddata-prod-pv-1"