---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqldataclaim
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: mysql