---
apiVersion: v1
kind: Service
metadata:
  name: owncloud-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: owncloud